export const CATEGORY_ATTRIBUTES = {
  Hotel: [
    "Early check-in",
    "Late check-out",
    "Bar",
    "Restaurant",
    "Pool",
    "Gym",
    "Free WiFi",
    "Airport shuttle",
    "Supermarket nearby",
    "Pharmacy nearby",
    "Meeting rooms",
    "Fuel/Charging nearby",
  ],
  Restaurant: [
    "Good for lunch meetings (quiet)",
    "Vegan options",
    "Vegetarian options",
    "Gluten-free options",
    "Outdoor seating",
    "Good for groups",
    "Takes reservations",
    "Good value",
  ],
  Bar: [
    "Good for groups",
    "Outdoor seating",
    "Sports TV",
    "Live music",
    "Good cocktails",
    "Food available",
  ],
  Cafe: [
    "Good for working (quiet)",
    "Fast WiFi",
    "Good coffee",
    "Food available",
    "Outdoor seating",
  ],
  Bakery: [
    "Fresh daily",
    "Gluten-free options",
    "Vegan options",
    "Eat in available",
  ],
  "Tourist Attraction": [
    "Guided tours",
    "Accessible",
    "Family friendly",
    "Skip-the-line tickets",
    "Photography allowed",
  ],
  Shopping: [
    "Accepts card",
    "Tax refund available",
    "Accessible",
    "Fitting rooms",
  ],
  Supermarket: [
    "Open late",
    "Self checkout",
    "Accepts card",
    "Pharmacy inside",
  ],
  "Taxi Rank": [
    "Fixed price",
    "Accepts card",
    "Available 24/7",
  ],
  Other: [],
};